notifications:
  webhooks:
    - https://webhook.commit-email.info/

language: cpp

apt_packages: &apt_packages
  packages:
    - autotools-dev
    - gdb
    - gtk-doc-tools
    - intltool
    - libgoffice-0.8-dev
    - libgstreamer0.10-dev
    - libgtk2.0-dev
    - libsoup2.4-dev

enable_coverage: &enable_coverage
  env:
    CONFIGURE_OPTIONS: --enable-coverage
  install:
    - sudo pip install cpp-coveralls
  after_success:
    - coveralls --exclude test

before_script:
  - ./autogen.sh
  - ./configure ${CONFIGURE_OPTIONS}

script:
  - test/run-test.sh

matrix:
  include:
    - name: "macOS"
      os: osx
      env:
        CONFIGURE_OPTIONS:
          PKG_CONFIG_PATH=$(brew --prefix libffi)/lib/pkgconfig
          PATH=$(brew --prefix gettext)/bin:${PATH}
      install:
        - brew update
        - brew bundle
        - brew list
      after_failure:
        - cat config.log
    - name: "GCC"
      os: linux
      compiler: gcc
      addons:
        apt:
          <<: *apt_packages
    - name: "GCC with coverage"
      os: linux
      compiler: gcc
      addons:
        apt:
          <<: *apt_packages
      <<: *enable_coverage
    - name: "Clang"
      os: linux
      compiler: clang
      addons:
        apt:
          <<: *apt_packages
    - name: "Clang with coverage"
      os: linux
      compiler: clang
      addons:
        apt:
          <<: *apt_packages
      <<: *enable_coverage
    - name: "macOS"
      os: osx
      env:
        CONFIGURE_OPTIONS:
          PKG_CONFIG_PATH="$(brew --prefix libffi)/lib/pkgconfig"
          PATH="$(brew --prefix gettext)/bin:${PATH}"
      install:
        - brew update
        - brew bundle
